export const ProjectMobile=[
        {id:1,name:  "iPhone 12", disc: "iPhone 12 with A14 chip", img: "https://www.91-img.com/gallery_images_uploads/0/e/0ebdcb79e919183de3974d52c5cbb60ae242bb4c.JPG?tr=h-550,w-0,c-at_max", price: 1000, category: "iphone", model: 2020, amount: 1, total: 0, storage: "64GB", ram: "4GB", camera: "12MP + 12MP", processor: "Apple A14 Bionic",fav:false,inCart:false},
        {id:2,name:  "iPhone 13", disc: "iPhone 13 with Super Retina Display", img: "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-12-r1.jpg", price: 1100, category: "iphone", model: 2021, amount: 1, total: 0, storage: "128GB", ram: "4GB", camera: "12MP + 12MP", processor: "Apple A15 Bionic",fav:false,inCart:false},
        {id:3,name:  "iPhone 14", disc: "iPhone 14 with Dynamic Island", img: "https://fdn2.gsmarena.com/vv/bigpic/xiaomi-redmi-note-13-5g.jpg", price: 1200, category: "iphone", model: 2022, amount: 1, total: 0, storage: "128GB", ram: "6GB", camera: "12MP + 12MP", processor: "Apple A15 Bionic",fav:false,inCart:false},
        {id:4,name:  "iPhone 11", disc: "iPhone 11 with Dual Cameras", img: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-13.jpg", price: 900, category: "iphone", model: 2019, amount: 1, total: 0, storage: "64GB", ram: "4GB", camera: "12MP + 12MP", processor: "Apple A13 Bionic",fav:false,inCart:false},
        {id:5,name:  "iPhone SE", disc: "iPhone SE with A13 Bionic", img: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-xr-new.jpg", price: 700, category: "iphone", model: 2020, amount: 1, total: 0, storage: "64GB", ram: "3GB", camera: "12MP", processor: "Apple A13 Bionic",fav:false,inCart:false},
        {id:6,name:  "iPhone XR", disc: "iPhone XR with Liquid Retina Display", img: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16-pro-max.jpg", price: 950, category: "iphone", model: 2018, amount: 1, total: 0, storage: "64GB", ram: "3GB", camera: "12MP", processor: "Apple A12 Bionic",fav:false,inCart:false},
        {id:7,name:  "iPhone 7", disc: "iPhone 7 with 12MP Camera", img: "https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-se-2022.jpg", price: 650, category: "iphone", model: 2016, amount: 1, total: 0, storage: "32GB", ram: "2GB", camera: "12MP", processor: "Apple A10 Fusion",fav:false,inCart:false},
   
        {id:8,name:  "Lenovo Legion Phone Duel 2", disc: "Gaming phone with dual cooling system", img: "https://fdn2.gsmarena.com/vv/bigpic/lenovo-legion-tab-gen3.jpg", price: 900, category: "lenovo", model: 2021, amount: 1, total: 0, storage: "512GB", ram: "16GB", camera: "64MP + 16MP", processor: "Snapdragon 888+",fav:false,inCart:false},
        {id:9,name:  "Lenovo Z6 Pro", disc: "Flagship smartphone with Snapdragon 855", img: "https://fdn2.gsmarena.com/vv/bigpic/lenovo-tab-m11.jpg", price: 650, category: "lenovo", model: 2019, amount: 1, total: 0, storage: "128GB", ram: "6GB", camera: "48MP + 16MP + 8MP", processor: "Snapdragon 855",fav:false,inCart:false},
        {id:10,name: "Lenovo K10 Note", disc: "Mid-range phone with triple camera setup", img: "https://fdn2.gsmarena.com/vv/bigpic/lenovo-legion-y700.jpg", price: 250, category: "lenovo", model: 2019, amount: 1, total: 0, storage: "64GB", ram: "4GB", camera: "16MP + 8MP + 5MP", processor: "Snapdragon 710",fav:false,inCart:false},
        {id:11,name: "Lenovo Vibe P1", disc: "Battery-focused phone with 5000mAh", img: "https://fdn2.gsmarena.com/vv/bigpic/lenovo-tab-p12-new.jpg", price: 200, category: "lenovo", model: 2015, amount: 1, total: 0, storage: "32GB", ram: "2GB", camera: "13MP", processor: "Qualcomm Snapdragon 615",fav:false,inCart:false},
        {id:12,name: "Lenovo A6000", disc: "Budget-friendly phone with 4G support",  img: "https://fdn2.gsmarena.com/vv/bigpic/lenovo-tab-m10-hd-gen2--.jpg", price: 150, category: "lenovo", model: 2015, amount: 1, total: 0, storage: "8GB", ram: "1GB", camera: "8MP", processor: "Qualcomm Snapdragon 410",fav:false,inCart:false},
        {id:13,name: "Lenovo Moto G5 Plus", disc: "Mid-range phone with 12MP camera", img: "https://fdn2.gsmarena.com/vv/bigpic/lenovo-tab-m8-HD.jpg", price: 300, category: "lenovo", model: 2017, amount: 1, total: 0, storage: "32GB", ram: "4GB", camera: "12MP", processor: "Qualcomm Snapdragon 625",fav:false,inCart:false},
        {id:14,name: "Lenovo Moto E5", disc: "Affordable phone with large display", img: "https://fdn2.gsmarena.com/vv/bigpic/lenovo-tab-plus.jpg", price: 180, category: "lenovo", model: 2018, amount: 1, total: 0, storage: "16GB", ram: "2GB", camera: "13MP", processor: "Qualcomm Snapdragon 430",fav:false,inCart:false},
        {id:15,name: "Lenovo Z5 Pro GT", disc: "Phone with pop-up camera and Snapdragon 855", img: "https://www.91-img.com/gallery_images_uploads/0/e/0ebdcb79e919183de3974d52c5cbb60ae242bb4c.JPG?tr=h-550,w-0,c-at_max", price: 400, category: "lenovo", model: 2019, amount: 1, total: 0, storage: "128GB", ram: "6GB", camera: "16MP + 24MP", processor: "Snapdragon 855",fav:false,inCart:false},
        {id:16,name: "Lenovo K8 Note", disc: "Dual rear cameras and 4GB RAM", img: "https://fdn2.gsmarena.com/vv/bigpic/lenovo-tab-m9.jpg", price: 220, category: "lenovo", model: 2017, amount: 1, total: 0, storage: "32GB", ram: "4GB", camera: "13MP + 5MP", processor: "MediaTek Helio X23",fav:false,inCart:false},
        {id:17,name: "Lenovo ThinkPhone", disc: "Enterprise-grade phone with rugged build", img: "https://fdn2.gsmarena.com/vv/bigpic/lenovo-s800.jpg", price: 500, category: "lenovo", model: 2023, amount: 1, total: 0, storage: "256GB", ram: "8GB", camera: "50MP", processor: "Qualcomm Snapdragon 8 Gen 1",fav:false,inCart:false},
     
        {id:18,name: "Samsung Galaxy S21", disc: "Flagship phone with 120Hz AMOLED display", img: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a55.jpg", price: 999, category: "samsung", model: 2021, amount: 1, total: 0, storage: "128GB", ram: "8GB", camera: "12MP + 64MP + 12MP", processor: "Exynos 2100 (Global) / Snapdragon 888 (USA)",fav:false,inCart:false},
        {id:19,name: "Samsung Galaxy S20", disc: "Flagship phone with 8K video recording", img: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a35.jpg", price: 850, category: "samsung", model: 2020, amount: 1, total: 0, storage: "128GB", ram: "8GB", camera: "12MP + 64MP + 12MP", processor: "Exynos 990 (Global) / Snapdragon 865 (USA)",fav:false,inCart:false},
        {id:20,name: "Samsung Galaxy Note 20 Ultra", disc: "Premium phone with 120Hz AMOLED display", img: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-5g-sm-s921.jpg", price: 1200, category: "samsung", model: 2020, amount: 1, total: 0, storage: "256GB", ram: "12GB", camera: "108MP + 12MP + 12MP", processor: "Exynos 990 (Global) / Snapdragon 865+ (USA)",fav:false,inCart:false},
        {id:21,name: "Samsung Galaxy A72", disc: "Mid-range phone with 90Hz display", img: "https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s24-ultra-5g-sm-s928-stylus.jpg", price: 450, category: "samsung", model: 2021, amount: 1, total: 0, storage: "128GB", ram: "6GB", camera: "64MP + 12MP + 8MP + 5MP", processor: "Qualcomm Snapdragon 720G",fav:false,inCart:false},
        {id:22,name: "Samsung Galaxy A52", disc: "Mid-range phone with 120Hz AMOLED display", img: "https://fdn.gsmarena.com/imgroot/news/25/01/galaxy-s25-s25-plus-s25-ultra-more-renders/-184x111/gsmarena_000.jpg", price: 400, category: "samsung", model: 2021, amount: 1, total: 0, storage: "128GB", ram: "4GB", camera: "64MP + 12MP + 5MP + 5MP", processor: "Qualcomm Snapdragon 720G",fav:false,inCart:false},
        {id:23,name: "Samsung Galaxy M32", disc: "Budget-friendly phone with 90Hz AMOLED display", img: "https://fdn.gsmarena.com/imgroot/news/25/01/samsung-galaxy-a36-charging/-184x111/gsmarena_000.jpg", price: 250, category: "samsung", model: 2021, amount: 1, total: 0, storage: "64GB", ram: "4GB", camera: "64MP + 8MP + 2MP + 2MP", processor: "MediaTek Helio G80",fav:false,inCart:false},
        {id:24,name: "Samsung Galaxy Z Flip 3", disc: "Foldable phone with AMOLED display", img: "https://fdn.gsmarena.com/imgroot/news/25/01/samsung-galaxy-s25-series-specs-leak/-184x111/gsmarena_000.jpg", price: 999, category: "samsung", model: 2021, amount: 1, total: 0, storage: "128GB", ram: "8GB", camera: "12MP + 12MP", processor: "Qualcomm Snapdragon 888",fav:false,inCart:false}
]


export const cart = []
export const favorit=[]